app:
  serverPort: :9000
  logLevel: debug

mysql:
  host: 127.0.0.1
  port: 3306
  database: eve
  username: root
  password: co9NAIXA4OHSHcSFdrSrK2fZ2yFGjKZasn0VTb1PQenoTcxB6EJNQl705DVbbWyR45X9/z3+2RtO/PZVKMVdwOGCvme4xGZB0+t+cvrCspQjcer8epmEihfJrzzSepflIE4SsWZHr/iBz90HDEz8wk0Jqqd2DhgT38vV5nt3mWE=
  charset: utf8
  loc: Asia/Shanghai
  maxIdleConn: 10
  maxOpenConn: 100
  connMaxLifetime: 600
  autoMigrate: false

redis:
  address: 127.0.0.1:6379
  password: co9NAIXA4OHSHcSFdrSrK2fZ2yFGjKZasn0VTb1PQenoTcxB6EJNQl705DVbbWyR45X9/z3+2RtO/PZVKMVdwOGCvme4xGZB0+t+cvrCspQjcer8epmEihfJrzzSepflIE4SsWZHr/iBz90HDEz8wk0Jqqd2DhgT38vV5nt3mWE=
  database: 0
  history_expire_time: -1
  order_expire_time: -1
  refresh: false

data: 
  local:  
    path: C://Users//Administrator//dev//data//
    refresh: false
  remote: 
    address: https://esi.evetech.net/latest
    datasource: tranquility
    refresh: false

crypto:
  keyPath: C://Users//Administrator//dev//data//private_key.pem
