app:
  serverPort: :9000
  logLevel: info

mysql:
  host: 127.0.0.1
  port: 3306
  database: eve
  username: root
  password: PTb+OMw67UKgiDKO34IkYEo1jnh0U7Iq7aiulo6cxY58ihvc9e+BUw6uboOWjzO8ZYa8IFlp8X2RInC7KZ0cT6X88+uwQ+pRPgEvO74k30aDnrRZREn5iUY/apC0tqIVW44NEAbpcYOpqLA3p2a1ZpgQ1s2PYPPF9d7IEY2FASY=
  charset: utf8
  loc: Asia/Shanghai
  maxIdleConn: 10
  maxOpenConn: 100
  connMaxLifetime: 600
  autoMigrate: false

redis:
  address: 127.0.0.1:6379
  password: aXsRmLMLWygWtIgDMNjCZNoy9w4X/rihrGMDwDexF+SQ5yjLPFfxvJBL0exAsWr1dzylhJljDgUZOu9k6F9WjzWcohkBkHB3wvaQrxHiwbuNv0ybMjQAZ56nKcZUbq275UNCBwiCm2+KoQjxqqJwdIOH+IJnyYKkJ3bTfDEwkHw=
  database: 0
  refresh: true
  expireTime:
    history: 51840
    order: 17280
    model: -1

data: 
  local:  
    path: /home/ubuntu/data
    refresh: false
  remote: 
    address: https://esi.evetech.net/latest
    datasource: tranquility
    refresh: false
    
crypto:
  keyPath: /home/ubuntu/crypto/private_key_prod.pem
