app:
  serverPort: 8000

mysql:
  host: 127.0.0.1
  port: 3306
  database: eve
  username: root
  password: changeit
  charset: utf8
  loc: Asia/Shanghai
  maxIdleConn: 10
  maxOpenConn: 100
  connMaxLifetime: 600
  autoMigrate: true

data: 
  refreshStaticData: true
  staticDataPath: C://Users//Administrator//dev//data//
  refreshRemoteData: true
  remoteDataAddress: https://esi.evetech.net/latest
  remoteDataSource: tranquility

